/**
 * Catálogo de permission_keys (coluna `permissions.permission_key`).
 * Os valores devem bater EXATAMENTE com o que está gravado no banco.
 * Espelha o enum de permissões do backoffice (nome da permissão).
 */
export enum PermissionKey {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_CONSULTANT = 'ROLE_CONSULTANT',
  ROLE_COLLECTION_AGENT = 'ROLE_COLLECTION_AGENT',
  ROLE_SUPPORT = 'ROLE_SUPPORT',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  QUOTE_CREATE = 'QUOTE_CREATE',
  QUOTE_VIEW_ALL = 'QUOTE_VIEW_ALL',
  QUOTE_APPROVER = 'QUOTE_APPROVER',
  QUOTE_VIEW_BUREAU_COMPLETE = 'QUOTE_VIEW_BUREAU_COMPLETE',
  CONTRACT_VIEW = 'CONTRACT_VIEW',
  CONTRACT_VIEW_ALL = 'CONTRACT_VIEW_ALL',
  CONTRACT_RENEGOTIATION_PROPOSE = 'CONTRACT_RENEGOTIATION_PROPOSE',
  CONTRACT_RENEGOTIATION_APPROVER = 'CONTRACT_RENEGOTIATION_APPROVER',
  CONTRACT_CREATE_QR_CODE = 'CONTRACT_CREATE_QR_CODE',
  CONTRACT_FOLLOW_UP = 'CONTRACT_FOLLOW_UP',
  INSTALLMENT_VIEW = 'INSTALLMENT_VIEW',
  INSTALLMENT_VIEW_ALL = 'INSTALLMENT_VIEW_ALL',
  INSTALLMENT_REPORT_EXPORT = 'INSTALLMENT_REPORT_EXPORT',
  CLIENT_VIEW_ALL = 'CLIENT_VIEW_ALL',
  CLIENT_REPORT_EXPORT = 'CLIENT_REPORT_EXPORT',
  MANUAL_PAYMENT_VIEW_ALL = 'MANUAL_PAYMENT_VIEW_ALL',
  MANUAL_PAYMENT_REPORT_EXPORT = 'MANUAL_PAYMENT_REPORT_EXPORT',
  MANUAL_PAYMENT_UPLOAD_BATCH = 'MANUAL_PAYMENT_UPLOAD_BATCH',
  USER_DELETE = 'USER_DELETE',
  ROLE_MANAGER = 'ROLE_MANAGER',
  ROLE_DIRECTOR = 'ROLE_DIRECTOR',
}
